version: '3'

services:
  app:
    image: node:18-alpine
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    depends_on:
      - mongo 
      - redis
    environment:
      - USER_TOKEN=${USER_TOKEN}
      - MONGO_URL=mongodb://mongo:27017/app
      - REDIS_URL=redis://redis:6379
      - BOT_TOKEN=${BOT_TOKEN}
    
  mongo:
    image: mongo:4.4.6
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none

  redis:
    image: redis:6.2.5
    ports:
      - 6007:6379
    volumes:
      - redis:/redis-data
    logging:
      driver: none

volumes:
  data:
  redis:
